# Generated by Django 4.0.6 on 2022-07-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buy_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=64)),
                ('link_man', models.CharField(max_length=64)),
                ('link_tel', models.CharField(max_length=64)),
                ('product_name', models.CharField(max_length=64)),
                ('product_num', models.IntegerField()),
                ('contract_no', models.IntegerField()),
                ('contract_menoy', models.IntegerField()),
                ('pay_menoy', models.IntegerField()),
                ('no_pay_meony', models.IntegerField()),
                ('delivery_date', models.DateTimeField(max_length=64)),
                ('isno_bill', models.CharField(max_length=64)),
                ('bill_date', models.DateTimeField(max_length=64)),
                ('send_goods_addr', models.CharField(max_length=64)),
                ('bill_addr', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='cunstomer_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cunstomer_name', models.CharField(max_length=128)),
                ('cunstomer_addr', models.CharField(default='', max_length=128)),
                ('link_name', models.CharField(default='', max_length=128)),
                ('link_tel', models.CharField(default='', max_length=128)),
                ('link_email', models.CharField(default='', max_length=128)),
                ('bank_num', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='goods_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=128)),
                ('product_num', models.CharField(default='', max_length=128)),
                ('product_specification', models.CharField(default='', max_length=128)),
                ('product_unit', models.CharField(default='', max_length=128)),
                ('product_color', models.CharField(default='', max_length=128)),
                ('product_model', models.CharField(default='', max_length=128)),
                ('product_type', models.CharField(default='', max_length=64)),
                ('product_weight', models.CharField(default='', max_length=64)),
                ('product_brand', models.CharField(default='', max_length=64)),
                ('product_attribute1', models.CharField(default='', max_length=64)),
                ('product_attribute2', models.CharField(default='', max_length=64)),
                ('product_attribute3', models.CharField(default='', max_length=64)),
                ('product_note', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='pay_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=32)),
                ('menoy', models.IntegerField()),
                ('note', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='sales_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('company_name', models.CharField(max_length=64)),
                ('link_man', models.CharField(max_length=64)),
                ('link_tel', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('company_addr', models.CharField(max_length=64)),
                ('duty_num', models.CharField(max_length=64)),
                ('bank_addr', models.CharField(max_length=64)),
                ('bank_num', models.IntegerField()),
                ('contract_no', models.IntegerField()),
                ('product_name', models.CharField(max_length=64)),
                ('product_num', models.IntegerField()),
                ('contract_menoy', models.IntegerField()),
                ('pay_menoy', models.IntegerField()),
                ('no_pay_meony', models.IntegerField()),
                ('delivery_date', models.DateTimeField(max_length=64)),
                ('isno_bill', models.CharField(max_length=64)),
                ('bill_date', models.DateTimeField(max_length=64)),
                ('pay_type', models.CharField(max_length=64)),
                ('send_goods_addr', models.CharField(max_length=64)),
                ('bill_addr', models.CharField(max_length=64)),
                ('note', models.CharField(max_length=64)),
                ('status', models.CharField(default='否', max_length=16)),
                ('img_path', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_addr', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=32)),
                ('sales_column', models.CharField(default='', max_length=256)),
                ('buy_column', models.CharField(default='', max_length=256)),
                ('goods_column', models.CharField(default='', max_length=256)),
                ('customer_column', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
