# Generated by Django 3.1.5 on 2021-03-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_info',
            name='status',
            field=models.CharField(default='否', max_length=16),
        ),
    ]
