# Generated by Django 3.1.5 on 2021-04-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_sales_info_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_info',
            name='img_path',
            field=models.CharField(default='', max_length=64),
        ),
    ]
