# Generated by Django 3.1.5 on 2021-04-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_sales_info_img_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_num', models.CharField(max_length=128)),
                ('product_name', models.CharField(max_length=128)),
                ('product_specification', models.CharField(default='', max_length=128)),
                ('product_unit', models.CharField(default='', max_length=128)),
                ('product_color', models.CharField(default='', max_length=128)),
                ('product_model', models.CharField(default='', max_length=128)),
                ('product_type', models.CharField(default='', max_length=64)),
                ('product_weight', models.CharField(default='', max_length=64)),
                ('product_brand', models.CharField(default='', max_length=64)),
                ('product_attribute1', models.CharField(default='', max_length=64)),
                ('product_attribute2', models.CharField(default='', max_length=64)),
                ('product_attribute3', models.CharField(default='', max_length=64)),
                ('product_note', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
