# Generated by Django 3.1.5 on 2021-04-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_goods_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='cunstomer_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cunstomer_name', models.CharField(max_length=128)),
                ('cunstomer_addr', models.CharField(default='', max_length=128)),
                ('link_name', models.CharField(default='', max_length=128)),
                ('link_tel', models.CharField(default='', max_length=128)),
                ('link_email', models.CharField(default='', max_length=128)),
                ('bank_num', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='stock_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('send_addr', models.CharField(max_length=128)),
            ],
        ),
    ]
