# Generated by Django 3.1.5 on 2021-04-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_cunstomer_info_stock_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='buy_column',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='customer_column',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='goods_column',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sales_column',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='goods_info',
            name='product_num',
            field=models.CharField(default='', max_length=128),
        ),
    ]
